<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Spesial di PSe Gameshop Hari ini</name>
   <tag></tag>
   <elementGuidId>da48ca85-a424-4efb-9536-2196f67a5e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-83532857']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>a40f1f18-8990-48bd-9cd8-83d3ed9e32ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spesial di PSe Gameshop Hari ini</value>
      <webElementGuid>560b9dde-5fd0-4e81-b0d5-90f2c350a36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-83532857&quot;)/h3[1]</value>
      <webElementGuid>e5a7c88d-25dc-43aa-ad70-08dd46d55b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-83532857']/h3</value>
      <webElementGuid>ef9b116a-c89c-4bbe-bcae-6ce145c55249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Button'])[2]/following::h3[1]</value>
      <webElementGuid>de79a826-248a-49d6-8ad8-69a9264999d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[2]/following::h3[1]</value>
      <webElementGuid>71cb9b03-120a-470d-a714-5c6aeab0b658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kejar Diskon Spesial'])[1]/preceding::h3[1]</value>
      <webElementGuid>736289a6-c034-4b90-85f4-cfab157765ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::h3[2]</value>
      <webElementGuid>f317d6d6-7f83-439c-a891-4875750be0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spesial di PSe Gameshop Hari ini']/parent::*</value>
      <webElementGuid>6eb841e8-f97f-4a94-b510-f34ee122d983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>8809736f-c581-420a-98d1-394f89654570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Spesial di PSe Gameshop Hari ini' or . = 'Spesial di PSe Gameshop Hari ini')]</value>
      <webElementGuid>45ecf726-1135-4c97-bdbf-0bbb9545a975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
